// Case studies. Source: _docs/01-CONTENT-SOURCE-OF-TRUTH.md §10–11 (TECH p9–15). No metrics beyond the decks.

export type Diagram =
  | { kind: "flow"; title: string; nodes: { title: string; body?: string }[]; tail?: { title: string; items: string[] } }
  | { kind: "layers"; title: string; layers: string[] }
  | { kind: "components"; title: string; items: string[] }
  | { kind: "fee-router"; title: string };

export type CaseStudy = {
  slug: string;
  index: string;
  name: string;
  category: string;
  practices: ("engineering" | "product-tokenomics")[];
  domains: { label: string; href: string }[];
  summary: string;
  challenge: string;
  engineered: string[];
  diagram: Diagram;
  stack: string[];
  status: "Live in production";
};

export const cases: CaseStudy[] = [
  {
    slug: "assymetrix",
    index: "01",
    name: "Assymetrix",
    category: "AI & Data Intelligence",
    practices: ["engineering"],
    domains: [
      { label: "assymetrix.com", href: "https://assymetrix.com" },
      { label: "data.assymetrix.com", href: "https://data.assymetrix.com" },
    ],
    summary: "Market intelligence across prediction-market venues.",
    challenge:
      "Every venue models markets, trades and outcomes its own way. The value is in comparing them in real time, which means getting them into one shape first.",
    engineered: [
      "A canonical schema that brings Polymarket, Kalshi, Limitless and 5+ other venues into one multi-terabyte dataset.",
      "AI engines that compare markets and surface arbitrage spreads, mispriced probabilities and yield strategies.",
      "TimescaleDB hypertables with compression and tiered retention, kept in real-time sync with automated recovery.",
    ],
    diagram: {
      kind: "flow",
      title: "System architecture",
      nodes: [
        { title: "Source ingestion", body: "Polymarket · Kalshi · Limitless · 5+ venues" },
        { title: "Canonical normalisation", body: "One schema for markets, trades & outcomes" },
        { title: "AI intelligence layer", body: "Arbitrage, mispricing & yield signals" },
      ],
    },
    stack: ["Node.js", "TypeScript", "PostgreSQL", "TimescaleDB", "Event-driven"],
    status: "Live in production",
  },
  {
    slug: "fincruse-crusex",
    index: "02",
    name: "Fincruse / CruseX",
    category: "Financial & Trading Infrastructure",
    practices: ["engineering"],
    domains: [{ label: "fincruse.com", href: "https://fincruse.com" }],
    summary: "Banking, trading, wallets and payments in one system.",
    challenge:
      "The platform needed exchange-quality order execution and bank-quality money movement in the same system, with no reconciliation gaps between the two.",
    engineered: [
      "An internal matching engine that fills orders user-to-user first and routes what’s left to external venues.",
      "A double-entry ledger with atomic transactions for deposits, withdrawals and wallet reconciliation.",
      "Transak for the on/off-ramp, Square for payments, and the CruseX HFT terminal with spot and demo trading.",
    ],
    diagram: {
      kind: "flow",
      title: "Order flow & settlement",
      nodes: [
        { title: "Internal matching engine", body: "User-to-user matching first" },
        { title: "External venue routing", body: "Binance · Coinbase · Bybit · B2broker" },
        { title: "Double-entry ledger", body: "Atomic settlement & reconciliation" },
      ],
    },
    stack: ["Matching engine", "Double-entry ledger", "Transak", "Fireblocks-ready"],
    status: "Live in production",
  },
  {
    slug: "goldpesa",
    index: "03",
    name: "Goldpesa",
    category: "DeFi & Tokenomics",
    practices: ["engineering", "product-tokenomics"],
    domains: [
      { label: "goldpesa.com", href: "https://goldpesa.com" },
      { label: "gpmines.com", href: "https://gpmines.com" },
    ],
    summary: "A DeFi ecosystem of several protocols, with rewards paid for by fees.",
    challenge:
      "Rewards had to be funded by real protocol activity instead of inflationary emissions, across several protocols that depend on each other.",
    engineered: [
      "“Mines”, a gamified staking product: users stake USDC, move up through levels and earn rewards generated by the protocol.",
      "GPO and GPX liquidity protocols (100M tokens each), with tokens released as demand grows and fees routed across the ecosystem.",
      "The GoldPesa Vault, where staked GPO converts 1:1 into GPX at set intervals and can be unstaked flexibly.",
    ],
    diagram: { kind: "fee-router", title: "Protocol fee routing" },
    stack: ["Solidity", "Tokenomics", "Liquidity protocols", "Vaults", "Fee routing"],
    status: "Live in production",
  },
  {
    slug: "invaria",
    index: "04",
    name: "INVARIA",
    category: "Enterprise AI & Trade Infrastructure",
    practices: ["engineering"],
    domains: [{ label: "invaria.digital", href: "https://invaria.digital" }],
    summary: "Decision infrastructure for global commodity trading.",
    challenge:
      "In commodity trading, credit and supply-chain decisions depend on counterparties and cargo you can’t simply take on trust.",
    engineered: [
      "An Entity Risk Calculator that uses AI to score revenue, liquidity, debt and jurisdictional risk, and turns the scores into credit decisions you can explain.",
      "VOSS, a live record of what is actually happening on the ground, built from GPS, maritime tracking, IoT and behavioural signals.",
      "A deterministic workflow engine, with documents fingerprinted on-chain across procurement, credit and logistics.",
    ],
    diagram: {
      kind: "layers",
      title: "Six-layer architecture",
      layers: [
        "Enterprise integrations",
        "Blockchain verification",
        "Real-time event infrastructure",
        "AI decision engines",
        "Workflow orchestration",
        "Presentation",
      ],
    },
    stack: ["React", "TypeScript", "Node.js", "PostgreSQL", "AI/ML", "On-chain proofs"],
    status: "Live in production",
  },
  {
    slug: "foreon-network",
    index: "05",
    name: "Foreon Network",
    category: "Protocol Engineering",
    practices: ["engineering", "product-tokenomics"],
    domains: [{ label: "foreon.network", href: "https://foreon.network" }],
    summary: "A prediction market built natively on Cardano, the first of its kind.",
    challenge:
      "Order books assume shared mutable state. Cardano’s UTxO model doesn’t have that, so trading had to be designed again from first principles.",
    engineered: [
      "Limit and market orders with partial fills, on an order book that lives fully on-chain and works with UTxOs natively.",
      "MarketFactory, escrow and treasury validators, and OutcomeToken minting policies, written in Aiken and Plutus.",
      "Oracle resolution with dispute windows, plus the transaction builders, event watchers and deployment tooling around it.",
    ],
    diagram: {
      kind: "components",
      title: "On-chain components",
      items: [
        "MarketFactory",
        "Escrow & treasury validators",
        "OutcomeToken minting policies",
        "On-chain order book",
        "Oracle resolution & disputes",
      ],
    },
    stack: ["Cardano", "Aiken", "Plutus", "UTxO", "Blockfrost", "Ogmios"],
    status: "Live in production",
  },
];

export const getCase = (slug: string) => cases.find((c) => c.slug === slug);

export type AdditionalWork = { tag: string; name: string; line: string; tone: "pink" | "violet" | "teal" };

export const additionalWork: AdditionalWork[] = [
  { tag: "NFT-Fi", name: "StreamNFT", line: "Staking, renting and loans for NFTs; contributed to ERC-7066", tone: "pink" },
  { tag: "Token launch", name: "PumpMarketCap", line: "On-chain launch & liquidity mechanics", tone: "pink" },
  { tag: "Gaming", name: "Luckify", line: "Provably fair play via Chainlink VRF", tone: "pink" },
  { tag: "GameFi", name: "Zuraverse", line: "NFT economies & tokenised item trading", tone: "pink" },
  { tag: "Identity · DAO", name: "CHOICE", line: "ZK-ready W3C DID identity & reputation", tone: "violet" },
  { tag: "Wallets", name: "BitDEX", line: "Multi-chain wallet & secure key handling", tone: "violet" },
  { tag: "Commerce", name: "droplinked", line: "NFT commerce with revenue sharing", tone: "violet" },
  { tag: "Ticketing", name: "eventflo", line: "On-chain tickets & fraud-resistant access", tone: "violet" },
  { tag: "RWA · ESG", name: "Web3Eco", line: "Tokenised plantations & profit cycles", tone: "teal" },
  { tag: "RWA", name: "Courtyard", line: "Custody & redemption of collectibles", tone: "teal" },
  { tag: "RWA · NDA", name: "PropertyVerse", line: "Fractional real-estate ledgers", tone: "teal" },
  { tag: "Creative", name: "ArtanAI", line: "NFT ownership with physical delivery", tone: "teal" },
];

/** All client names from the decks, for the wordmark marquee (text only — no logos exist). */
export const clientNames = [
  ...cases.map((c) => c.name),
  ...additionalWork.map((w) => w.name),
];
